In [6]:
import cv2
from PIL import Image
import numpy as np
img_path = './ADE20k_toy_dataset/annotations/training/ADE_train_00000001.png'
img_path2 = './custom_dataset/annotations/training/SC_PAR_20220831_155720_cam01.png'
img = cv2.imread(img_path)
img2 = cv2.imread(img_path2)
# print(img.shape, img2.shape)

print('img',img)
print('img2',img2)

# segmentation_maps = Image.open(img_path)
# print(segmentation_maps.mode)
# segmentation_maps2 = Image.open(img_path2)
# print(segmentation_maps2.mode)

# if segmentation_maps is not None:
#     if isinstance(segmentation_maps, (Image.Image, np.ndarray)):
#         valid_segmentation_maps = True
#     elif isinstance(segmentation_maps, (list, tuple)):
#         if len(segmentation_maps) == 0 or isinstance(segmentation_maps[0], (Image.Image, np.ndarray)):
#             valid_segmentation_maps = True

#     if not valid_segmentation_maps:
#         raise ValueError(
#             "Segmentation maps must of type `PIL.Image.Image` or `np.ndarray` (single example),"
#             "`List[PIL.Image.Image]` or `List[np.ndarray]` (batch of examples)."
#         )



# segmentation_maps = [segmentation_maps2]

# for idx, map in enumerate(segmentation_maps):
#     if not isinstance(map, np.ndarray):
#         print('dd')
#         map = np.array(map)
#     # avoid using underflow conversion
#     print(map.shape)
#     map[map == 0] = 255
#     map = map - 1
#     map[map == 254] = 255
#     print(map.shape)
#     segmentation_maps[idx] = Image.fromarray(map.astype(np.uint8))


img [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 [[0 0 0]
  [0 0 0]
  [6 6 6]
  ...
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 [[0 0 0]
  [0 0 0]
  [6 6 6]
  ...
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 ...

 [[4 4 4]
  [4 4 4]
  [4 4 4]
  ...
  [1 1 1]
  [1 1 1]
  [0 0 0]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]
  ...
  [1 1 1]
  [1 1 1]
  [0 0 0]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
img2 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ...

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  ...
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  ...
  [7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]
  ...
  [7 7 7]
  [7 7 7]
  [7 7 7]]]


In [3]:
from PIL import Image
import cv2
img_path = './ADE20k_toy_dataset/images/training/ADE_train_00000001.jpg'

img = cv2.imread(img_path)
segmentation_maps = Image.open(img_path)
segmentation_maps.mode

'RGB'